/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KartyaKitalalo;

/**
 *
 * @author Mágori Ferenc
 */
public class KartyaKitalaloGUI extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KartyaKitalaloGUI.class.getName());

    /**
     * Creates new form KartyaKitalaloGUI
     */
    public KartyaKitalaloGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_leiras = new javax.swing.JLabel();
        pnl_oszlop1 = new javax.swing.JPanel();
        pnl_kartya = new javax.swing.JPanel();
        lbl_kartyaSzin = new javax.swing.JLabel();
        lbl_kartyaErtek = new javax.swing.JLabel();
        pnl_kartya1 = new javax.swing.JPanel();
        lbl_kartyaSzin1 = new javax.swing.JLabel();
        lbl_kartyaErtek1 = new javax.swing.JLabel();
        pnl_oszlop2 = new javax.swing.JPanel();
        pnl_kartya3 = new javax.swing.JPanel();
        lbl_kartyaSzin3 = new javax.swing.JLabel();
        lbl_kartyaErtek3 = new javax.swing.JLabel();
        pnl_kartya2 = new javax.swing.JPanel();
        lbl_kartyaSzin2 = new javax.swing.JLabel();
        lbl_kartyaErtek2 = new javax.swing.JLabel();
        pnl_oszlop3 = new javax.swing.JPanel();
        pnl_kartya4 = new javax.swing.JPanel();
        lbl_kartyaSzin4 = new javax.swing.JLabel();
        lbl_kartyaErtek4 = new javax.swing.JLabel();
        pnl_kartya5 = new javax.swing.JPanel();
        lbl_kartyaSzin5 = new javax.swing.JLabel();
        lbl_kartyaErtek5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        bttn_oszlop1 = new javax.swing.JButton();
        bttn_oszlop2 = new javax.swing.JButton();
        bttn_oszlop3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kártya Kitatáló");
        setLocationByPlatform(true);
        setName(""); // NOI18N

        lbl_leiras.setText("Gondolj egy kártyára, majd válaszd ki, melyik oszlopban van!");

        pnl_oszlop1.setBorder(javax.swing.BorderFactory.createTitledBorder("1.oszlop"));
        pnl_oszlop1.setPreferredSize(new java.awt.Dimension(150, 300));

        lbl_kartyaSzin.setText("KártyaSzín");

        lbl_kartyaErtek.setText("KártyaÉrték");

        javax.swing.GroupLayout pnl_kartyaLayout = new javax.swing.GroupLayout(pnl_kartya);
        pnl_kartya.setLayout(pnl_kartyaLayout);
        pnl_kartyaLayout.setHorizontalGroup(
            pnl_kartyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_kartyaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_kartyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_kartyaLayout.createSequentialGroup()
                        .addComponent(lbl_kartyaSzin)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_kartyaLayout.createSequentialGroup()
                        .addComponent(lbl_kartyaErtek)
                        .addContainerGap())))
        );
        pnl_kartyaLayout.setVerticalGroup(
            pnl_kartyaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_kartyaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_kartyaSzin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_kartyaErtek)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        lbl_kartyaSzin1.setText("KártyaSzín");

        lbl_kartyaErtek1.setText("KártyaÉrték");

        javax.swing.GroupLayout pnl_kartya1Layout = new javax.swing.GroupLayout(pnl_kartya1);
        pnl_kartya1.setLayout(pnl_kartya1Layout);
        pnl_kartya1Layout.setHorizontalGroup(
            pnl_kartya1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_kartya1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_kartya1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_kartya1Layout.createSequentialGroup()
                        .addComponent(lbl_kartyaSzin1)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_kartya1Layout.createSequentialGroup()
                        .addComponent(lbl_kartyaErtek1)
                        .addContainerGap())))
        );
        pnl_kartya1Layout.setVerticalGroup(
            pnl_kartya1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_kartya1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_kartyaSzin1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_kartyaErtek1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_oszlop1Layout = new javax.swing.GroupLayout(pnl_oszlop1);
        pnl_oszlop1.setLayout(pnl_oszlop1Layout);
        pnl_oszlop1Layout.setHorizontalGroup(
            pnl_oszlop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_oszlop1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_oszlop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_kartya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_kartya1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnl_oszlop1Layout.setVerticalGroup(
            pnl_oszlop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_oszlop1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnl_kartya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_kartya1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(116, 116, 116))
        );

        pnl_oszlop2.setBorder(javax.swing.BorderFactory.createTitledBorder("2.oszlop"));
        pnl_oszlop2.setPreferredSize(new java.awt.Dimension(150, 300));

        lbl_kartyaSzin3.setText("KártyaSzín");

        lbl_kartyaErtek3.setText("KártyaÉrték");

        javax.swing.GroupLayout pnl_kartya3Layout = new javax.swing.GroupLayout(pnl_kartya3);
        pnl_kartya3.setLayout(pnl_kartya3Layout);
        pnl_kartya3Layout.setHorizontalGroup(
            pnl_kartya3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_kartya3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_kartya3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_kartya3Layout.createSequentialGroup()
                        .addComponent(lbl_kartyaSzin3)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_kartya3Layout.createSequentialGroup()
                        .addComponent(lbl_kartyaErtek3)
                        .addContainerGap())))
        );
        pnl_kartya3Layout.setVerticalGroup(
            pnl_kartya3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_kartya3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_kartyaSzin3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_kartyaErtek3)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        lbl_kartyaSzin2.setText("KártyaSzín");

        lbl_kartyaErtek2.setText("KártyaÉrték");

        javax.swing.GroupLayout pnl_kartya2Layout = new javax.swing.GroupLayout(pnl_kartya2);
        pnl_kartya2.setLayout(pnl_kartya2Layout);
        pnl_kartya2Layout.setHorizontalGroup(
            pnl_kartya2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_kartya2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_kartya2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_kartya2Layout.createSequentialGroup()
                        .addComponent(lbl_kartyaSzin2)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_kartya2Layout.createSequentialGroup()
                        .addComponent(lbl_kartyaErtek2)
                        .addContainerGap())))
        );
        pnl_kartya2Layout.setVerticalGroup(
            pnl_kartya2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_kartya2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_kartyaSzin2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_kartyaErtek2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_oszlop2Layout = new javax.swing.GroupLayout(pnl_oszlop2);
        pnl_oszlop2.setLayout(pnl_oszlop2Layout);
        pnl_oszlop2Layout.setHorizontalGroup(
            pnl_oszlop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_oszlop2Layout.createSequentialGroup()
                .addGroup(pnl_oszlop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_kartya3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_kartya2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 68, Short.MAX_VALUE))
        );
        pnl_oszlop2Layout.setVerticalGroup(
            pnl_oszlop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_oszlop2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_kartya3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_kartya2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(212, 212, 212))
        );

        pnl_oszlop3.setBorder(javax.swing.BorderFactory.createTitledBorder("3.oszlop"));
        pnl_oszlop3.setPreferredSize(new java.awt.Dimension(150, 300));

        lbl_kartyaSzin4.setText("KártyaSzín");

        lbl_kartyaErtek4.setText("KártyaÉrték");

        javax.swing.GroupLayout pnl_kartya4Layout = new javax.swing.GroupLayout(pnl_kartya4);
        pnl_kartya4.setLayout(pnl_kartya4Layout);
        pnl_kartya4Layout.setHorizontalGroup(
            pnl_kartya4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_kartya4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_kartya4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_kartya4Layout.createSequentialGroup()
                        .addComponent(lbl_kartyaSzin4)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_kartya4Layout.createSequentialGroup()
                        .addComponent(lbl_kartyaErtek4)
                        .addContainerGap())))
        );
        pnl_kartya4Layout.setVerticalGroup(
            pnl_kartya4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_kartya4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_kartyaSzin4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_kartyaErtek4)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        lbl_kartyaSzin5.setText("KártyaSzín");

        lbl_kartyaErtek5.setText("KártyaÉrték");

        javax.swing.GroupLayout pnl_kartya5Layout = new javax.swing.GroupLayout(pnl_kartya5);
        pnl_kartya5.setLayout(pnl_kartya5Layout);
        pnl_kartya5Layout.setHorizontalGroup(
            pnl_kartya5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_kartya5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_kartya5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_kartya5Layout.createSequentialGroup()
                        .addComponent(lbl_kartyaSzin5)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_kartya5Layout.createSequentialGroup()
                        .addComponent(lbl_kartyaErtek5)
                        .addContainerGap())))
        );
        pnl_kartya5Layout.setVerticalGroup(
            pnl_kartya5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_kartya5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_kartyaSzin5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_kartyaErtek5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_oszlop3Layout = new javax.swing.GroupLayout(pnl_oszlop3);
        pnl_oszlop3.setLayout(pnl_oszlop3Layout);
        pnl_oszlop3Layout.setHorizontalGroup(
            pnl_oszlop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_oszlop3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_oszlop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_kartya4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_kartya5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        pnl_oszlop3Layout.setVerticalGroup(
            pnl_oszlop3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_oszlop3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_kartya4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_kartya5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(139, 139, 139))
        );

        jLabel1.setText("Kártya amire gondoltál:");
        jLabel1.setToolTipText("");

        jTextField1.addActionListener(this::jTextField1ActionPerformed);

        bttn_oszlop1.setText("Kiválaszt 1.oszlop");

        bttn_oszlop2.setText("Kiválaszt 2.oszlop");

        bttn_oszlop3.setText("Kiválaszt 3.oszlop");

        jLabel2.setText("1. kör / 3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_leiras, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(pnl_oszlop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(bttn_oszlop1)
                                        .addGap(32, 32, 32)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(bttn_oszlop2))
                                    .addComponent(pnl_oszlop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(bttn_oszlop3))
                                    .addComponent(pnl_oszlop3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel2)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_leiras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_oszlop1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_oszlop2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnl_oszlop3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bttn_oszlop3)
                    .addComponent(bttn_oszlop2)
                    .addComponent(bttn_oszlop1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(188, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KartyaKitalaloGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn_oszlop1;
    private javax.swing.JButton bttn_oszlop2;
    private javax.swing.JButton bttn_oszlop3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbl_kartyaErtek;
    private javax.swing.JLabel lbl_kartyaErtek1;
    private javax.swing.JLabel lbl_kartyaErtek2;
    private javax.swing.JLabel lbl_kartyaErtek3;
    private javax.swing.JLabel lbl_kartyaErtek4;
    private javax.swing.JLabel lbl_kartyaErtek5;
    private javax.swing.JLabel lbl_kartyaSzin;
    private javax.swing.JLabel lbl_kartyaSzin1;
    private javax.swing.JLabel lbl_kartyaSzin2;
    private javax.swing.JLabel lbl_kartyaSzin3;
    private javax.swing.JLabel lbl_kartyaSzin4;
    private javax.swing.JLabel lbl_kartyaSzin5;
    private javax.swing.JLabel lbl_leiras;
    private javax.swing.JPanel pnl_kartya;
    private javax.swing.JPanel pnl_kartya1;
    private javax.swing.JPanel pnl_kartya2;
    private javax.swing.JPanel pnl_kartya3;
    private javax.swing.JPanel pnl_kartya4;
    private javax.swing.JPanel pnl_kartya5;
    private javax.swing.JPanel pnl_oszlop1;
    private javax.swing.JPanel pnl_oszlop2;
    private javax.swing.JPanel pnl_oszlop3;
    // End of variables declaration//GEN-END:variables
}
